name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install Python virtualenv
        run: pip3 install virtualenv
      - name: Setup virtualenv
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Activate and install dependencies into venv
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Install dependencies for testing
        run: pip3 install -r requirements.txt
      - name: Build and run tests
        run: . venv/bin/activate && pytest
      - name: Create a zip file of dependencies
        run: |
          cd ./venv/lib/python3.7/site-packages
          zip -r9 ../../../../api.zip .
      - name: Add app files to zip
        run: cd ./app && zip -g ../api.zip -r .
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
  continuous-deployment:
    runs-on: ubuntu-latest
    needs:
      - continuos-integration
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact api.zip
        uses: actions/download-artifact@v2
        with:
          name: api
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ always() }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: my-github-actions-role
          aws-region: us-east-2
      - name: Upload to S3 Bucket
        run: |
          aws s3 cp api.zip s3://serverless-luis-api/serverless-api.zip
      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code --function-name serverless-luis-api --s3-bucket serverless-luis-api --s3-key api.zip